version: "3.8"

services:
  web-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      - DATABASE_HOST=${DATABASE_HOST:-db}
      - DATABASE_PORT=${DATABASE_PORT:-5432}
      - DATABASE_USER=${DATABASE_USER:-user}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD:-password}
      - DATABASE_NAME=${DATABASE_NAME:-dbname}
      - DATABASE_URL=postgres://${DATABASE_USER}:${DATABASE_PASSWORD}@${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    networks:
      - app-network

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ${DATABASE_USER:-user}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD:-password}
      POSTGRES_DB: ${DATABASE_NAME:-dbname}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
