version: "3.8"

services:
  web-app:
    build: .
    ports:
      - "3000:3000"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - app-network

  db:
    image: postgres:13
    env_file:
      - .env
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
